spring.application.name=BankingSystem
spring.main.allow-bean-definition-overriding=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.protocol=smtp

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Optional app properties
app.mail.from.address=no-reply@smartbanking.local
app.mail.from.name=SmartBanking
app.mail.otp.subject=Your SmartBanking OTP